version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: lienas/reverseproxy
  backend_user:
    build:
      context: ../../udagram-api-users
    image: lienas/udagram-api-users
  backend_feed:
    build:
      context: ../../udagram-api-feeds
    image: lienas/udagram-api-feed
  frontend:
    build:
      context: ../../udagram-frontend
    image: lienas/udagram-frontend
